import Link from "next/link";
import "@/lib/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="container mx-auto my-10">
        <nav className="bg-gray-200 py-2 px-4 rounded-md flex gap-x-5">
          <Link href="/">Home</Link>
          <Link href="/notes">Notes</Link>
        </nav>
        <main className="mt-10">{children}</main>
      </body>
    </html>
  );
};

export default Layout;
